<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7bI3j2Z\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7bI3j2Z/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7bI3j2Z.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7bI3j2Z\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7bI3j2Z\App_KernelDevDebugContainer([
    'container.build_hash' => '7bI3j2Z',
    'container.build_id' => '02841097',
    'container.build_time' => 1631266684,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7bI3j2Z');
